name: OpenCC Convert

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20     # Fetch 20 recent commits

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'        # caching pip dependencies

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Convert zh-hant
        run: |
          ls -lah
          git log
          python3 scripts/convert_zh.py
          
          # If the hash is the only thing that's changed, don't commit
          if [["$(git diff --numstat | wc -l)" == "1"]]
            git reset –hard
          fi

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: '[U] Generate zh_hant from zh_hans'
  
  
